# Generated by Django 5.0.6 on 2024-05-21 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjmgmt_anuncios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagensanuncio',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imagensanuncio',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagensanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mjmgmt_anuncios.anuncio'),
        ),
    ]
